import { Category, Difficulty } from '@/types'

export const TEXT_CATEGORIES: Record<Category, string[]> = {
  quotes: [
    "The quick brown fox jumps over the lazy dog. This sentence contains every letter of the alphabet.",
    "Programming is the art of telling another human being what one wants the computer to do.",
    "The best way to predict the future is to invent it. Computer science is no more about computers than astronomy is about telescopes.",
    "Code is like humor. When you have to explain it, it's bad. Clean code always looks like it was written by someone who cares.",
    "First, solve the problem. Then, write the code. Any fool can write code that a computer can understand. Good programmers write code that humans can understand.",
    "The only way to learn a new programming language is by writing programs in it. The more you code, the better you become.",
    "Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it.",
    "Simplicity is the ultimate sophistication. The best code is code that is easy to read and understand.",
    "Programs must be written for people to read, and only incidentally for machines to execute. Code readability is paramount.",
    "The most important property of a program is whether it accomplishes the intention of its user. Functionality over complexity.",
    "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.",
    "The best programs are written so that computing machines can perform them quickly and so that human beings can understand them clearly.",
    "Programming is not about typing, it's about thinking. The keyboard is just a tool for expressing your thoughts.",
    "The best error message is the one that never appears. Write code that prevents errors before they happen.",
    "Code never lies, comments sometimes do. Write self-documenting code that explains itself through clear naming.",
    "The goal is not to write code that works, but to write code that works and is maintainable for years to come.",
    "A good programmer is someone who looks both ways before crossing a one-way street. Always think about edge cases.",
    "The best way to get a project done faster is to start sooner. Planning saves time in the long run.",
    "There are only two kinds of programming languages: those people always complain about and those nobody uses.",
    "The most disastrous thing that you can ever learn is your first programming language. It shapes how you think.",
  ],
  programming: [
    "const fetchData = async () => { const response = await fetch('/api/data'); return response.json(); }",
    "function binarySearch(arr, target) { let left = 0, right = arr.length - 1; while (left <= right) { const mid = Math.floor((left + right) / 2); if (arr[mid] === target) return mid; arr[mid] < target ? left = mid + 1 : right = mid - 1; } return -1; }",
    "class Component extends React.Component { constructor(props) { super(props); this.state = { count: 0 }; } render() { return <div>{this.state.count}</div>; } }",
    "const debounce = (func, wait) => { let timeout; return function executedFunction(...args) { const later = () => { clearTimeout(timeout); func(...args); }; clearTimeout(timeout); timeout = setTimeout(later, wait); }; };",
    "interface User { id: number; name: string; email: string; } const users: User[] = [{ id: 1, name: 'John', email: 'john@example.com' }];",
    "const useCounter = () => { const [count, setCount] = useState(0); const increment = () => setCount(count + 1); return [count, increment]; };",
    "const map = new Map(); map.set('key', 'value'); const value = map.get('key'); console.log(value);",
    "const filterEven = (arr) => arr.filter(num => num % 2 === 0); const numbers = [1, 2, 3, 4, 5]; console.log(filterEven(numbers));",
    "const reducer = (state, action) => { switch(action.type) { case 'INCREMENT': return { count: state.count + 1 }; default: return state; } };",
    "const memoizedValue = useMemo(() => expensiveCalculation(a, b), [a, b]); const callback = useCallback(() => { doSomething(a, b); }, [a, b]);",
    "const router = createRouter({ history: createWebHistory(), routes: [{ path: '/', component: Home }] });",
    "const schema = z.object({ name: z.string().min(1), email: z.string().email() }); const result = schema.parse(data);",
    "const query = useQuery(['todos'], fetchTodos); const mutation = useMutation(createTodo, { onSuccess: () => query.invalidate(); });",
    "const middleware = (req, res, next) => { console.log('Request:', req.method, req.path); next(); }; app.use(middleware);",
    "const promise = new Promise((resolve, reject) => { setTimeout(() => resolve('Success'), 1000); }); promise.then(console.log);",
    "const asyncFunction = async () => { try { const data = await fetch('/api'); return await data.json(); } catch (error) { console.error(error); } };",
    "const sorted = array.sort((a, b) => a.value - b.value); const unique = [...new Set(array)]; const sum = array.reduce((acc, val) => acc + val, 0);",
    "const Component = ({ title, children }) => { useEffect(() => { document.title = title; }, [title]); return <div>{children}</div>; };",
    "const context = createContext(); const Provider = ({ children }) => { const value = { state, setState }; return <context.Provider value={value}>{children}</context.Provider>; };",
    "const styled = styled.div` color: ${props => props.color}; padding: 20px; `; const Button = styled.button` background: blue; `;",
  ],
  random: [
    "The mysterious package arrived on a Tuesday morning, wrapped in brown paper and tied with string. Inside, there was nothing but a single key and a note that read: 'The adventure begins now.'",
    "She walked through the ancient forest, where sunlight filtered through the canopy in golden streams. Every step crunched on fallen leaves, and the air smelled of damp earth and pine.",
    "The old lighthouse stood tall against the stormy sky, its beam cutting through the darkness like a sword. Waves crashed against the rocky shore, sending spray high into the air.",
    "In the heart of the city, neon signs flickered to life as dusk settled. Crowds of people moved like rivers through the streets, each person lost in their own world of thoughts and destinations.",
    "The recipe called for three cups of flour, two eggs, and a pinch of magic. As she mixed the ingredients, the batter began to glow with an otherworldly light, promising something extraordinary.",
    "The clock struck midnight as the last train pulled away from the station. She stood alone on the platform, watching the red lights disappear into the darkness, wondering if she had made the right choice.",
    "Beneath the surface of the calm lake, ancient secrets lay hidden. The diver descended slowly, his flashlight cutting through the murky water, revealing glimpses of a forgotten world below.",
    "The library was a sanctuary of silence, where time seemed to stand still. Rows upon rows of books stretched into the distance, each one holding stories waiting to be discovered.",
    "The mountain peak pierced through the clouds like a needle through fabric. From this height, the world below looked like a miniature model, peaceful and perfect from afar.",
    "The coffee shop buzzed with morning energy. Baristas called out orders, steam rose from espresso machines, and the aroma of freshly ground beans filled the air with warmth and comfort.",
    "The old typewriter sat on the desk, its keys yellowed with age. Each letter pressed was a commitment, no backspace, no delete, just the permanent mark of thought made tangible.",
    "The garden bloomed with colors that seemed impossible in the gray city. Flowers of every hue created a tapestry of life, a small rebellion against the concrete and steel surrounding it.",
    "The bridge connected two worlds, spanning the river that had divided them for centuries. People crossed daily, carrying their hopes and dreams from one side to the other.",
    "The telescope pointed toward the stars, its lens capturing light that had traveled millions of years to reach this moment. In the darkness, the universe revealed its infinite beauty.",
    "The market square came alive at dawn. Vendors arranged their wares, fresh produce glistened with morning dew, and the first customers arrived, seeking the day's best finds.",
    "The old piano in the corner had not been played in years, but its keys still held the memory of melodies long forgotten. One touch, and the music would return.",
    "The path through the woods was well-worn, trodden by countless feet over generations. Each step connected the walker to those who had journeyed this way before.",
    "The window framed a perfect view of the sunset, painting the sky in shades of orange and pink. For a moment, time stopped, and there was only beauty.",
    "The workshop smelled of sawdust and oil, tools hanging in perfect order on the walls. Here, raw materials transformed into works of art through skill and patience.",
    "The letter arrived on a rainy afternoon, its envelope slightly damp. Inside, words that would change everything, written in handwriting that was both familiar and foreign.",
  ],
  literature: [
    "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity.",
    "In a hole in the ground there lived a hobbit. Not a nasty, dirty, wet hole, filled with the ends of worms and an oozy smell, nor yet a dry, bare, sandy hole with nothing in it to sit down on or to eat: it was a hobbit-hole, and that means comfort.",
    "Call me Ishmael. Some years ago—never mind how long precisely—having little or no money in my purse, and nothing particular to interest me on shore, I thought I would sail about a little and see the watery part of the world.",
    "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife. However little known the feelings or views of such a man may be on his first entering a neighbourhood, this truth is so well fixed in the minds of the surrounding families.",
    "The sun was shining on the sea, shining with all his might: He did his very best to make the billows smooth and bright—And this was odd, because it was the middle of the night.",
    "All happy families are alike; each unhappy family is unhappy in its own way. The Oblonsky household was in confusion.",
    "It was a bright cold day in April, and the clocks were striking thirteen. Winston Smith, his chin nuzzled into his breast in an effort to escape the vile wind, slipped quickly through the glass doors of Victory Mansions.",
    "The past is a foreign country; they do things differently there. When I was a child, I thought that grown-ups never cried.",
    "There was no possibility of taking a walk that day. We had been wandering, indeed, in the leafless shrubbery an hour in the morning; but since dinner the cold winter wind had brought with it clouds so sombre, and a rain so penetrating.",
    "The sky above the port was the color of television, tuned to a dead channel. It's not like I'm using, Case heard someone say, as he shouldered his way through the crowd around the door of the Chat.",
    "The man in black fled across the desert, and the gunslinger followed. The desert was the apotheosis of all deserts, huge, standing to the sky for what looked like eternity in all directions.",
    "It was a pleasure to burn. It was a special pleasure to see things eaten, to see things blackened and changed. With the brass nozzle in his fists, with this great python spitting its venomous kerosene upon the world.",
    "The story so far: in the beginning, the universe was created. This has made a lot of people very angry and been widely regarded as a bad move.",
    "The primroses were over. Toward the edge of the wood, where the ground became open and sloped down to an old fence and a brambly ditch beyond, only a few fading patches of pale yellow still showed among the dog's mercury and oak-tree roots.",
    "The sun shone, having no alternative, on the nothing new. Murphy sat out of it, as though he were free, in a mew in West Brompton.",
    "The tower, which was not supposed to be there, plunges into the earth in a place just before the black pine forest begins to give way to swamp and then the reeds and wind-gnarled trees of the marsh flats.",
    "The building was on fire, and it wasn't my fault. I stood on the roof of the building, watching the flames consume the structure below me.",
    "The waystone was his, just as the third silence was his. This was appropriate, as it was the greatest silence of the three, wrapping the others inside itself.",
    "The man who was not Terrence O'Grady had come to the end of his rope. He had been running for three days now, and he was tired.",
    "The first thing you find out when yer dog learns to talk is that dogs don't got nothing much to say. About anything. 'Call me,' my dog says. 'Call me.'",
  ],
}

export const DIFFICULTY_LENGTHS: Record<Difficulty, number> = {
  easy: 50,
  medium: 100,
  hard: 200,
}
